heliport/cwl_execution/urls.py
# SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""Map django views to urls.

See this :ref:`django:topics/http/urls:example` including explanation from the Django
documentation.
"""

from django.urls import path
from rest_framework import routers

from .views import (
    ArbitraryCWLListView,
    ArbitraryCWLUpdateView,
    ExecutableRawJsonView,
    ExecutableRawYamlView,
    ExecutableViewSet,
    ExecutionLogViewSet,
    JobCreateView,
    JobDebugView,
    JobDetailView,
    JobListView,
    JobOutputView,
    JobParameterValueView,
    JobProfilingJsonView,
    JobRawYamlView,
    JobStartView,
    JobStopView,
    JobViewSet,
    PublicationWorkflowCreateView,
    RunningJobsView,
    SearchView,
    ToolCreateView,
    ToolJsonDescriptionView,
    ToolListView,
    ToolUpdateView,
    UserJobConfigViewSet,
    VisualizationDataView,
    WorkflowCreateView,
    WorkflowListView,
    WorkflowUpdateView,
)

app_name = "cwl_execution"
urlpatterns = [
    path(
        "project/<int:project>/cwl-execution/arbitrary-cwl/list/",
        ArbitraryCWLListView.as_view(),
        name="arbitrary_cwl_list",
    ),
    path(
        "project/<int:project>/cwl-execution/arbitrary-cwl/<int:pk>/update/",
        ArbitraryCWLUpdateView.as_view(),
        name="arbitrary_cwl_update",
    ),
    path(
        "project/<int:project>/cwl-execution/job/create-from/<int:executable>/",
        JobCreateView.as_view(),
        name="job_create",
    ),
    path(
        "project/<int:project>/cwl-execution/job/publication-workflow/new/",
        PublicationWorkflowCreateView.as_view(),
        name="publication_workflow_create",
    ),
    path(
        "project/<int:project>/cwl-execution/job/parameter-value/new/",
        JobParameterValueView.as_view(),
        name="parameter_value",
    ),
    path(
        "project/<int:project>/cwl-execution/executable/<int:executable>/job/<int:pk>/update/",
        JobCreateView.as_view(),
        name="job_update",
    ),
    path(
        "project/<int:project>/cwl-execution/job/list/",
        JobListView.as_view(),
        name="job_list",
    ),
    path(
        "project/<int:project>/cwl-execution/job/running/",
        RunningJobsView.as_view(),
        name="job_running",
    ),
    path(
        "project/<int:project>/cwl-execution/job/<int:pk>/start/",
        JobStartView.as_view(),
        name="job_start",
    ),
    path(
        "project/<int:project>/cwl-execution/job/<int:pk>/CWL/YAML/",
        JobRawYamlView.as_view(),
        name="job_cwl_yaml",
    ),
    path(
        "project/<int:project>/cwl-execution/job/<int:pk>/detail/",
        JobDetailView.as_view(),
        name="job_detail",
    ),
    path(
        "project/<int:project>/cwl-execution/job/<int:pk>/output/",
        JobOutputView.as_view(),
        name="job_output",
    ),
    path(
        "project/<int:project>/cwl-execution/job/<int:pk>/debug/",
        JobDebugView.as_view(),
        name="job_debug",
    ),
    path(
        "project/<int:project>/cwl-execution/job/<int:pk>/stop/",
        JobStopView.as_view(),
        name="job_stop",
    ),
    path(
        "project/<int:project>/cwl-execution/job/<int:pk>/profiling/json/",
        JobProfilingJsonView.as_view(),
        name="job_profiling_json",
    ),
    path(
        "project/<int:project>/cwl-execution/tool/list/",
        ToolListView.as_view(),
        name="tool_list",
    ),
    path(
        "cwl-execution/tool/<int:pk>/CWL/YAML/",
        ExecutableRawYamlView.as_view(),
        name="exe_cwl_yaml",
    ),
    path(
        "cwl-execution/tool/<int:pk>/CWL/YAML/<str:part>/",
        ExecutableRawYamlView.as_view(),
        name="exe_cwl_yaml",
    ),
    path(
        "cwl-execution/tool/<int:pk>/CWL/JSON/",
        ExecutableRawJsonView.as_view(),
        name="exe_cwl_json",
    ),
    path(
        "cwl-execution/tool/<int:pk>/CWL/JSON/<str:part>/",
        ExecutableRawJsonView.as_view(),
        name="exe_cwl_json",
    ),
    path(
        "project/<int:project>/cwl-execution/tool/<int:pk>/description/",
        ToolJsonDescriptionView.as_view(),
        name="tool_description",
    ),
    path(
        "project/<int:project>/cwl-execution/tool/<int:pk>/update/",
        ToolUpdateView.as_view(),
        name="tool_update",
    ),
    path(
        "project/<int:project>/cwl-execution/tool/create/",
        ToolCreateView.as_view(),
        name="tool_create",
    ),
    path(
        "project/<int:project>/cwl-execution/workflow/list/",
        WorkflowListView.as_view(),
        name="workflow_list",
    ),
    path(
        "project/<int:project>/cwl-execution/workflow/<int:pk>/update/",
        WorkflowUpdateView.as_view(),
        name="workflow_update",
    ),
    path(
        "project/<int:project>/cwl-execution/workflow/create/",
        WorkflowCreateView.as_view(),
        name="workflow_create",
    ),
    path(
        "project/<int:project>/cwl-execution/executable/<int:pk>/visualization-data/",
        VisualizationDataView.as_view(),
        name="visualization_data",
    ),
    path("cwl-execution/search/", SearchView.as_view(), name="search"),
]

# REST API
router = routers.DefaultRouter()
router.register(r"cwl-execution/executables", ExecutableViewSet, basename="executables")
router.register(r"cwl-execution/jobs", JobViewSet, basename="job")
router.register(
    r"cwl-execution/user-job-configs", UserJobConfigViewSet, basename="user_job_configs"
)
router.register(
    r"cwl-execution/execution-logs", ExecutionLogViewSet, basename="execution_logs"
)

heliport_config/urls.py
# noqa: D100
# SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: GPL-3.0-or-later

from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from rest_framework import routers

from heliport.archive.urls import router as archive_router
from heliport.core.urls import router as core_router
from heliport.cwl_execution.urls import router as cwl_router
from heliport.data_management_plan.urls import router as dmp_router
from heliport.data_source.urls import router as data_source_router
from heliport.digital_objects.urls import router as digital_objects_router
from heliport.documentation.urls import router as documentation_router
from heliport.publication.urls import router as publication_router
from heliport.sharelatex.urls import router as sharelatex_router
from heliport.smb_files.urls import router as smb_router
from heliport.ssh.urls import router as ssh_router
from heliport.version_control.urls import router as version_control_router

urlpatterns = [
    # django.contrib apps
    path("admin/", admin.site.urls),
    # Third-party apps
    path("__debug__/", include("debug_toolbar.urls")),
    path("accounts/", include("allauth.urls")),
    path("health/", include("health_check.urls")),
    path("qr-code/", include("qr_code.urls", namespace="qr_code")),
    # heliport apps
    path("", include("heliport.core.urls")),
    path("", include("heliport.archive.urls")),
    path("", include("heliport.cwl_execution.urls")),
    path("", include("heliport.data_management_plan.urls")),
    path("", include("heliport.data_source.urls")),
    path("", include("heliport.digital_objects.urls")),
    path("", include("heliport.documentation.urls")),
    path("", include("heliport.publication.urls")),
    path("", include("heliport.sharelatex.urls")),
    path("", include("heliport.smb_files.urls")),
    path("", include("heliport.ssh.urls")),
    path("", include("heliport.tables.urls")),
    path("", include("heliport.version_control.urls")),
]

api_routers = [
    core_router,
    archive_router,
    cwl_router,
    dmp_router,
    data_source_router,
    digital_objects_router,
    documentation_router,
    publication_router,
    sharelatex_router,
    smb_router,
    ssh_router,
    version_control_router,
]

if settings.HELIPORT_GATE_ENABLED:
    from heliport.gate_connection.urls import router as gate_connection_router

    urlpatterns.append(path("", include("heliport.gate_connection.urls")))
    api_routers.append(gate_connection_router)

if settings.HELIPORT_UNICORE_ENABLED:
    urlpatterns.append(path("", include("heliport.unicore.urls")))

router = routers.DefaultRouter()
for api_router in api_routers:
    router.registry.extend(api_router.registry)

urlpatterns.append(path("api/", include(router.urls)))

heliport/cwl_execution/models.py
# SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""Contains :class:`django.db.models.Model` classes for Django ORM.

See :ref:`django:topics/db/models:quick example` from Django documentation.
In HELIPORT the :class:`heliport.core.models.DigitalObject` can be subclassed for models
containing metadata in a project.
"""

import json

from django.db import models
from django.utils import timezone

from heliport.core.models import DigitalObject, HeliportUser, LoginInfo

from .cwl_helpers.cwl_parameter import CwlParameter


def json_load_dict(json_string, error_dict=None):  # noqa: D103
    if error_dict is None:
        error_dict = {}

    try:
        cwl = json.loads(json_string)
    except ValueError:
        cwl = error_dict
    except TypeError:
        cwl = error_dict

    if not isinstance(cwl, dict):
        cwl = error_dict

    return cwl


class Executable(DigitalObject):  # noqa: D101
    class ExecutableTypes(models.IntegerChoices):  # noqa: D106
        TOOL = 1
        WORKFLOW = 2
        ARBITRARY_CWL = 3

    class CWLTypes(models.IntegerChoices):  # noqa: D106
        YAML = 2
        JSON = 1

    executable_id = models.AutoField(primary_key=True)
    cwl_json = models.TextField(blank=True, default="")
    cwl_is_public = models.BooleanField(default=False)
    cwl_type = models.IntegerField(choices=CWLTypes.choices, default=CWLTypes.JSON)
    type = models.IntegerField(choices=ExecutableTypes.choices)
    download_url_is_public = models.BooleanField(default=False)

    original_id = models.CharField(max_length=100, null=True, blank=True)  # noqa: DJ001

    def uses_files(self):  # noqa: D102
        try:
            cwl = json_load_dict(self.cwl_json, {"inputs": {}})
            inputs = cwl["inputs"]
            if isinstance(inputs, dict):
                inputs = inputs.values()
            return any(param["type"] == "File" for param in inputs)
        except KeyError:
            return False

    @property
    def cwl(self):  # noqa: D102
        return json_load_dict(
            self.cwl_json, {"label": "SYNTAX ERROR", "doc": "SYNTAX ERROR IN JSON"}
        )

    @cwl.setter
    def cwl(self, cwl_dict):
        assert isinstance(cwl_dict, dict), "can only set dict as cwl attribute"
        self.cwl_json = json.dumps(cwl_dict, sort_keys=False)
        self.label = cwl_dict.get("label", "")
        self.description = cwl_dict.get("doc", "")

    @property
    def job_count(self):  # noqa: D102
        return len(self.job_set.filter(deleted__isnull=True))

    @property
    def parameters(self):  # noqa: D102
        parameters = self.cwl.get("inputs", [])
        if isinstance(parameters, dict):
            parameters = [{"id": key, **values} for key, values in parameters.items()]

        return [
            CwlParameter(
                p.get("id", "INVALID"), p.get("type", "no_type"), p.get("label", "")
            )
            for p in parameters
        ]


class Job(DigitalObject):  # noqa: D101
    class OutputCodes(models.IntegerChoices):  # noqa: D106
        UNDEFINED = -1
        MESSAGE = 0
        WARNING = 1
        ERROR = 2

    class StatusCodes(models.TextChoices):  # noqa: D106
        RUNNING = "Running"
        PAUSED = "Paused"
        STOPPED = "Stopped"

    job_id = models.AutoField(primary_key=True)
    status = models.CharField(
        max_length=80, choices=StatusCodes.choices, default=StatusCodes.STOPPED
    )
    output_text = models.TextField()
    output_code = models.IntegerField(
        choices=OutputCodes.choices, default=OutputCodes.UNDEFINED
    )
    cwl_json = models.TextField(blank=True, default="")
    repeat = models.BooleanField(default=False)
    interval = models.IntegerField(default=0)
    base_executable = models.ForeignKey(Executable, on_delete=models.CASCADE)
    setup_command = models.TextField(blank=True)
    cmd_options = models.TextField(blank=True, default="--time=10")

    original_id = models.CharField(max_length=100, null=True, blank=True)  # noqa: DJ001

    def __str__(self):  # noqa: D105
        return str(self.label)

    @property
    def cwl(self):  # noqa: D102
        return json_load_dict(self.cwl_json, {"SYNTAX ERROR": "SYNTAX ERROR IN JSON"})


class UserJobConfig(models.Model):  # noqa: D101
    user_job_config_id = models.AutoField(primary_key=True)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    ssh_login = models.ForeignKey(LoginInfo, on_delete=models.SET_NULL, null=True)
    directory = models.TextField()

    original_id = models.CharField(max_length=100, null=True, blank=True)  # noqa: DJ001

    def __str__(self):  # noqa: D105
        return f"{self.job} config ({self.pk})"

    @property
    def projects(self):  # noqa: D102
        return self.job.projects


class ExecutionLog(models.Model):  # noqa: D101
    execution_log_id = models.AutoField(primary_key=True)
    config = models.ForeignKey(UserJobConfig, on_delete=models.CASCADE)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField(null=True, blank=True)
    memory_usage = models.TextField(default="")
    execution_id = models.TextField(null=True, blank=True)  # noqa: DJ001
    aborted = models.BooleanField(default=False)
    step_times = models.TextField(null=True, blank=True)  # noqa: DJ001
    output_code = models.IntegerField(
        choices=Job.OutputCodes.choices, default=Job.OutputCodes.UNDEFINED
    )
    error_message = models.TextField(blank=True)
    user = models.ForeignKey(HeliportUser, null=True, on_delete=models.SET_NULL)

    original_id = models.CharField(max_length=100, null=True, blank=True)  # noqa: DJ001

    def __str__(self):  # noqa: D105
        return f"{str(self.config.job)} log ({self.pk})"

    def get_user(self):  # noqa: D102
        config = self.config
        login = config.ssh_login if config is not None else None
        user = login.user if login is not None else None
        return self.user or user

    def start(self, execution_id=None):  # noqa: D102
        self.start_time = timezone.now()
        self.execution_id = execution_id
        self.save()

    def stop(self, kill=False):  # noqa: D102
        self.end_time = timezone.now()
        self.aborted = kill
        self.save()

    @property
    def duration(self):  # noqa: D102
        if self.end_time is not None:
            return self.end_time - self.start_time
        return timezone.now() - self.start_time

    @property
    def seconds_since_start(self):  # noqa: D102
        return (timezone.now() - self.start_time).total_seconds()

    @property
    def duration_str(self):  # noqa: D102
        total_seconds = int(self.duration.total_seconds())

        days = total_seconds // 86400
        remaining_hours = total_seconds % 86400
        remaining_minutes = remaining_hours % 3600
        hours = remaining_hours // 3600
        minutes = remaining_minutes // 60
        seconds = remaining_minutes % 60

        days_str = f"{days}d " if days else ""
        hours_str = f"{hours}h " if hours else ""
        minutes_str = f"{minutes}m " if minutes else ""
        seconds_str = f"{seconds}s" if seconds and not hours_str else ""

        return f"{days_str}{hours_str}{minutes_str}{seconds_str}"

    @property
    def memory_usage_dict(self):  # noqa: D102
        return json_load_dict(self.memory_usage)

    @property
    def memory_usage_bytes(self):  # noqa: D102
        return {
            key: self.parse_memory_units(value)
            for key, value in self.memory_usage_dict.items()
        }

    @staticmethod
    def parse_memory_units(memory_with_unit):  # noqa: D102
        if memory_with_unit.isdecimal():
            return int(memory_with_unit)
        for unit, factor in {
            "B": 1,
            "KiB": 1024**1,
            "MiB": 1024**2,
            "GiB": 1024**3,
            "TiB": 1024**4,
            "PiB": 1024**5,
            "KB": 1000**1,
            "MB": 1000**2,
            "GB": 1000**3,
            "TB": 1000**4,
            "PB": 1000**5,
        }.items():
            memory_str = memory_with_unit.split(unit)[0]
            if memory_str.isdecimal():
                return int(memory_str) * factor
        return None

    @property
    def profiling(self):  # noqa: D102
        if self.step_times:
            return json.loads(self.step_times)
        return None

heliport/cwl_execution/templates/cwl_execution/job_list.html
{% extends "core/base/base.html" %}
{% comment %}
SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)

SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}
{% load static %}
{% block content %}
  <h3>Jobs</h3>
  {% if userjobconfigs %}
    <table class="table">
      <tr>
        <th style="width: 10%;">ID</th>
        <th style="width: 10%;">Name</th>
        <th style="width: 20%;">Cluster Login</th>
        <th style="width: 20%;">Directory on Cluster</th>
        <th class="text-center">Status</th>
        <th></th>
      </tr>
      {% for userjobconfig in userjobconfigs %}
        <tr>
          <td class="align-middle">{{ userjobconfig.job.pk }} / {{ userjobconfig.pk }}</td>
          <td class="align-middle">{{ userjobconfig.job.label }}</td>
          <td class="align-middle">
            {% if ssh_logins %}
              <select class="form-select"
                      id="login_{{ userjobconfig.pk }}"
                      name="job_ssh_login"
                      required="required">
                <option disabled selected>Choose a Login</option>
                {% for login in ssh_logins %}
                  <option value="{{ login.pk }}"
                          {% if login == userjobconfig.ssh_login %}selected{% endif %}>{{ login.name }}</option>
                {% endfor %}
              </select>
            {% endif %}
          </td>
          <td class="align-middle">
            <input class="form-control"
                   id="directory_{{ userjobconfig.pk }}"
                   name="job_location"
                   value="{{ userjobconfig.directory }}" />
          </td>
          <td class="text-center align-middle" id="status">
            {% if userjobconfig.job.status == userjobconfig.job.StatusCodes.RUNNING %}
              <div class="spinner-border text-success"
                   style="width: 1.5em;
                          height: 1.5em">
                <span class="visually-hidden"></span>
              </div>
            {% elif userjobconfig.job.status == userjobconfig.job.StatusCodes.PAUSED %}
              <i class="fa-solid fa-circle-xmark fa-xl text-warning" title="Paused"></i>
            {% else %}
              {% if userjobconfig.job.output_code == userjobconfig.job.OutputCodes.MESSAGE %}
                <i class="fa-solid fa-circle-check fa-xl text-success" title="Success"></i>
              {% elif userjobconfig.job.output_code == userjobconfig.job.OutputCodes.WARNING %}
                <i class="fa-solid fa-circle-exclamation fa-xl text-warning"
                   title="Warning"></i>
              {% elif userjobconfig.job.output_code == userjobconfig.job.OutputCodes.ERROR %}
                <i class="fa-solid fa-circle-xmark fa-xl text-danger" title="Error"></i>
              {% endif %}
            {% endif %}
          </td>
          <td class="text-end">
            <a style="margin: 0.25em"
               href="{% url 'cwl_execution:job_update' project.pk userjobconfig.job.base_executable.pk userjobconfig.job.pk %}"
               class="btn btn-primary"
               title="Edit">
              <i class="fa-solid fa-pencil"></i>
            </a>
            {% if userjobconfig.job.status == userjobconfig.job.StatusCodes.RUNNING %}
              <button style="margin: 0.25em"
                      onclick="get_and_reload('{% url 'cwl_execution:job_stop' project.pk userjobconfig.pk %}')"
                      type="button"
                      class="btn btn-primary"
                      {% if not ssh_logins %}disabled{% endif %}
                      title="Stop Job">
                <i class="fa-solid fa-stop"></i>
              </button>
            {% else %}
              <button style="margin: 0.25em"
                      onclick="start_job('{% url 'cwl_execution:job_start' project.pk userjobconfig.pk %}', '{{ userjobconfig.pk }}')"
                      type="button"
                      class="btn btn-primary"
                      {% if not ssh_logins %}disabled{% endif %}
                      title="Start Job">
                <i class="fa-solid fa-play"></i>
              </button>
            {% endif %}
            <button style="margin: 0.25em"
                    onclick="start_job('{% url 'cwl_execution:job_debug' project.pk userjobconfig.pk %}', '{{ userjobconfig.pk }}')"
                    type="button"
                    class="btn btn-primary"
                    {% if not ssh_logins %}disabled{% endif %}
                    title="Run in Debug Mode">
              <i class="fa-solid fa-bug"></i>
            </button>
            <a style="margin: 0.25em"
               href="{% url 'cwl_execution:job_cwl_yaml' project.pk userjobconfig.job.pk %}"
               class="btn btn-primary {% if not ssh_logins %}disabled{% endif %}"
               title="Open CWL">
              <i class="fa-solid fa-code"></i>
            </a>
            <a style="margin: 0.25em"
               class="btn btn-primary {% if not ssh_logins %}disabled{% endif %}"
               href="{% url 'cwl_execution:job_detail' project.pk userjobconfig.job.pk %}"
               title="Output and Details">
              <i class="fa-solid fa-eye"></i>
            </a>
            <form action="{% url 'cwl_execution:job_list' project.pk %}"
                  method="post"
                  style="display: inline">
              {% csrf_token %}
              <button style="margin: 0.25em"
                      action="submit"
                      class="btn btn-danger"
                      name="delete"
                      value="{{ userjobconfig.job.pk }}"
                      title="Delete Job">
                <i class="fa-solid fa-trash"></i>
              </button>
            </form>
          </td>
        </tr>
      {% endfor %}
    </table>
    {% if not ssh_logins %}
      <div class="alert alert-danger" role="alert">
        <small>You have no login yet. Create one <a href="{% url 'core:user_login_list' %}">here</a>.</small>
      </div>
    {% endif %}
  {% endif %}
  <div class="container">
    <div class="row">
      <div class="col-md d-grid" style="padding-bottom: 0.5em;">
        <a class="btn btn-primary text-nowrap"
           href="{% url 'cwl_execution:tool_list' project.pk %}">Add from Tool</a>
      </div>
      <div class="col-md d-grid" style="padding-bottom: 0.5em;">
        <a class="btn btn-primary text-nowrap"
           href="{% url 'cwl_execution:workflow_list' project.pk %}">Add from Workflow</a>
      </div>
      <div class="col-md d-grid" style="padding-bottom: 0.5em;">
        <a class="btn btn-primary text-nowrap"
           href="{% url 'cwl_execution:arbitrary_cwl_list' project.pk %}">Add from Arbitrary CWL</a>
      </div>
      <div class="col-md d-grid" style="padding-bottom: 0.5em;">
        <a class="btn btn-primary text-nowrap"
           href="{% url 'cwl_execution:publication_workflow_create' project.pk %}">Create Publication Job</a>
      </div>
    </div>
  </div>
{% endblock content %}
{% block script %}
  <script>
        let running = {{ running }};
        let running_str = running.sort().join(";");

        function refresh_if_running_changed() {
            $.get("{% url 'cwl_execution:job_running' project.pk %}", function (data) {
                if (data.running.sort().join(";") !== running_str) location.reload();
            });
        }

        if (running.length > 0) setInterval(refresh_if_running_changed, 3000);

        function get_and_reload(url) {
            $.get(url)
            setTimeout(() => window.location.reload(), 500);
        }
        function start_job(base_url, job_id){
            let url = new URL(window.location)
            url.pathname = base_url
            url.searchParams.append("login", $("#login_" + job_id).val())
            url.searchParams.append("directory", $("#directory_" + job_id).val())
            get_and_reload(url.href)
        }
  </script>
{% endblock script %}

heliport/cwl_execution/templates/cwl_execution/tool_list.html
{% extends "core/base/base.html" %}
{% comment %}
SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)

SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}
{% load static %}
{% block content %}
  <div class="row">
    <div class="col">
      <h3>Tools</h3>
      {% if tools %}
        <form method="post">
          {% csrf_token %}
          <table class="table">
            <tr>
              <th style="width: 10%;">ID</th>
              <th style="width: 20%;">Base Command</th>
              <th style="width: 22%;">Description</th>
              <th></th>
            </tr>
            {% for tool in tools %}
              <tr>
                <td class="align-middle">{{ tool.executable_id }}</td>
                <td class="align-middle">{{ tool.cwl.baseCommand }}</td>
                <td class="align-middle">{{ tool.cwl.label }}</td>
                <td class="align-middle">
                  <div class="container">
                    <div class="row">
                      <div class="col-md d-grid text-nowrap"
                           style="padding-left: 0.5em;
                                  padding-right: 0;
                                  padding-top: 0.25em;
                                  padding-bottom: 0.25em">
                        <a class="btn btn-primary"
                           href="{% url 'cwl_execution:job_create' project.pk tool.pk %}">Execute ({{ tool.job_count }})</a>
                      </div>
                      <div class="col-md d-grid"
                           style="padding-left: 0.5em;
                                  padding-right: 0;
                                  padding-top: 0.25em;
                                  padding-bottom: 0.25em">
                        <a class="btn btn-secondary text-nowrap"
                           href="{% url 'cwl_execution:exe_cwl_yaml' tool.pk %}">Open raw</a>
                      </div>
                      <div class="col-md d-grid"
                           style="padding-left: 0.5em;
                                  padding-right: 0;
                                  padding-top: 0.25em;
                                  padding-bottom: 0.25em">
                        <a class="btn btn-secondary"
                           href="{% url 'cwl_execution:tool_update' project.pk tool.pk %}">Edit</a>
                      </div>
                      <div class="col-md d-grid"
                           style="padding-left: 0.5em;
                                  padding-right: 0;
                                  padding-top: 0.25em;
                                  padding-bottom: 0.25em">
                        <button class="btn btn-danger"
                                type="submit"
                                name="delete"
                                value="{{ tool.pk }}">Delete</button>
                      </div>
                    </div>
                  </div>
                </td>
              </tr>
            {% endfor %}
          </table>
        </form>
      {% else %}
        <br />
      {% endif %}
      <a class="btn btn-primary"
         style="margin-left: 0.75rem;
                margin-bottom: 1em"
         href="{% url 'cwl_execution:tool_create' project.pk %}">Create Tool</a>
    </div>
  </div>
{% endblock content %}