heliport/core/urls.py
# SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""Map django views to urls.

See this :ref:`django:topics/http/urls:example` including explanation from the Django
documentation.
"""

from django.conf import settings
from django.urls import include, path, re_path, reverse_lazy
from django.views.decorators.cache import cache_page
from django.views.generic import RedirectView
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView
from rest_framework import routers

from .views.api import (
    ContributionViewSet,
    DeleteAllTokensView,
    DigitalObjectAPI,
    GroupViewSet,
    LoginNamedTokenView,
    LogoutTokenView,
    MaintenanceMessageView,
    ProjectViewSet,
    TokenViewSet,
    UserViewSet,
)
from .views.digital_objects import AsDigitalObjectView, DigitalObjectAutocompleteView
from .views.images import ImagesView, ImageView, TakePictureView
from .views.landing_page import IndexView, LandingPageView, ResolveDigitalObjectView
from .views.project import (
    CreateProjectView,
    CreateSampleProjectView,
    ImportFromProjectView,
    OpenInProjectView,
    ProjectGraphView,
    ProjectListView,
    ProjectTimelineView,
    ProjectUpdateView,
    ProjectView,
    SubprojectsView,
    get_users_autocomplete,
)
from .views.search import SearchBaseView, SearchView
from .views.tags import TagAutocompleteView, TagJsonView, TagsView
from .views.user import (
    LoginInfoUpdateView,
    LoginInfoView,
    RemoteServerLoginView,
    RemoteServerLogoutView,
    TokenListView,
    UserProfileView,
)

app_name = "core"
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path(
        "about/",
        RedirectView.as_view(url=settings.HELIPORT_CORE_ABOUT_URL),
        name="about",
    ),
    path(
        "docs/", RedirectView.as_view(url=settings.HELIPORT_CORE_DOCS_URL), name="docs"
    ),
    path(
        "imprint/",
        RedirectView.as_view(url=settings.HELIPORT_CORE_IMPRINT_URL),
        name="imprint",
    ),
    path(
        "privacy/",
        RedirectView.as_view(url=settings.HELIPORT_CORE_PRIVACY_URL),
        name="privacy",
    ),
    path(
        "terms/", RedirectView.as_view(url=settings.HELIPORT_CORE_TOS_URL), name="tos"
    ),
    path(
        "cite/", RedirectView.as_view(url=settings.HELIPORT_CORE_CITE_URL), name="cite"
    ),
    # Auth is handled by allauth. The login, logout, and register URLs are kept for
    # their nice paths and potentially widely used names.
    path(
        "login/", RedirectView.as_view(url=reverse_lazy("account_login")), name="login"
    ),
    path(
        "logout/",
        RedirectView.as_view(url=reverse_lazy("account_logout")),
        name="logout",
    ),
    path(
        "register/",
        RedirectView.as_view(url=reverse_lazy("account_signup")),
        name="register",
    ),
    path("user/profile/", UserProfileView.as_view(), name="user_profile"),
    path("user/token/list/", TokenListView.as_view(), name="user_token_list"),
    path(
        "user/logout-all-tokens/",
        DeleteAllTokensView.as_view(),
        name="logout_all_tokens",
    ),
    path("user/login/list/", LoginInfoView.as_view(), name="user_login_list"),
    path(
        "user/login/<int:pk>/update/",
        LoginInfoUpdateView.as_view(),
        name="user_login_update",
    ),
    path(
        "user/login/remote-server-login/<int:pk>/",
        RemoteServerLoginView.as_view(),
        name="remote_server_login",
    ),
    path(
        "user/login/remote-server-logout/<int:pk>/",
        RemoteServerLogoutView.as_view(),
        name="remote_server_logout",
    ),
    path(
        "digital-object-autocomplete/",
        DigitalObjectAutocompleteView.as_view(),
        name="digital_object_autocomplete",
    ),
    # Redirect landing page URLs with missing "H" prefix.
    path(
        "object/<int:pk>/",
        RedirectView.as_view(
            permanent=True, pattern_name="core:landing_page", query_string=True
        ),
        name="legacy_landing_page",
    ),
    # Prefix "H" is required for XML serialization to work!
    path("object/H<int:pk>/", LandingPageView.as_view(), name="landing_page"),
    re_path(
        "object/(?P<identifier>.+)$",  # No trailing slash!
        ResolveDigitalObjectView.as_view(),
        name="resolve_digital_object_id",
    ),
    path("project/<int:project>/image/list/", ImagesView.as_view(), name="image_list"),
    path(
        "project/<int:project>/image/take/",
        TakePictureView.as_view(),
        name="take_image",
    ),
    path(
        "image/<int:pk>/data/",
        cache_page(4 * 24 * 60 * 60, cache="image_cache")(ImageView.as_view()),
        name="image_data",
    ),
    path("project/<int:project>/tag/list/", TagsView.as_view(), name="tag_list"),
    path(
        "project/<int:project>/tag/<int:pk>/update/",
        TagsView.as_view(),
        name="tag_update",
    ),
    path(
        "project/<int:project>/tag/list/json/",
        TagJsonView.as_view(),
        name="tag_json",
    ),
    path(
        "project/<int:project>/tag/autocomplete/",
        TagAutocompleteView.as_view(),
        name="tag_autocomplete",
    ),
    path(
        "project/<int:project>/subprojects/",
        SubprojectsView.as_view(),
        name="subprojects",
    ),
    path(
        "project/<int:project>/import/",
        ImportFromProjectView.as_view(),
        name="import_project",
    ),
    path("project/list/", ProjectListView.as_view(), name="project_list"),
    path(
        "project/create/sample/",
        CreateSampleProjectView.as_view(),
        name="project_create_sample",
    ),
    path("project/create/", CreateProjectView.as_view(), name="project_create"),
    path(
        "project/<int:project>/graph/", ProjectGraphView.as_view(), name="project_graph"
    ),
    path(
        "project/<int:project>/timeline/",
        ProjectTimelineView.as_view(),
        name="project_timeline",
    ),
    path("project/<int:project>/", ProjectView.as_view(), name="project"),
    path(
        "project/<int:project>/update/",
        ProjectUpdateView.as_view(),
        name="project_update",
    ),
    path("project/<int:project>/autocomplete-user/", get_users_autocomplete),
    path("search-base/", SearchBaseView.as_view(), name="search_base"),
    path("search/", SearchView.as_view(), name="search"),
    path(
        "project/<int:project>/as-digital-object/",
        AsDigitalObjectView.as_view(),
        name="as_digital_object",
    ),
    path(
        "project/<int:project>/redirect/",
        OpenInProjectView.as_view(),
        name="open_in_project",
    ),
]

# REST API
router = routers.DefaultRouter()
router.register(r"projects", ProjectViewSet, basename="projects")
router.register(r"users", UserViewSet, basename="users")
router.register(r"groups", GroupViewSet, basename="groups")
router.register(r"contributions", ContributionViewSet, basename="contributions")
router.register(r"tokens", TokenViewSet, basename="tokens")
router.register(
    r"digital-objects/complete", DigitalObjectAPI, basename="digital-objects-complete"
)

urlpatterns += [
    path("api/auth/delete-token/", LogoutTokenView.as_view(), name="delete_token"),
    path("api/auth/login-named/", LoginNamedTokenView.as_view(), name="login_named"),
    path("api/auth/", include("knox.urls")),
    path(
        "api/maintenance-message/",
        MaintenanceMessageView.as_view(),
        name="maintenance_message",
    ),
    path("openapi/", SpectacularAPIView.as_view(), name="openapi-schema"),
    path(
        "redoc/",
        SpectacularRedocView.as_view(url_name="core:openapi-schema"),
        name="redoc",
    ),
]

heliport_config/urls.py
# noqa: D100
# SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: GPL-3.0-or-later

from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from rest_framework import routers

from heliport.archive.urls import router as archive_router
from heliport.core.urls import router as core_router
from heliport.cwl_execution.urls import router as cwl_router
from heliport.data_management_plan.urls import router as dmp_router
from heliport.data_source.urls import router as data_source_router
from heliport.digital_objects.urls import router as digital_objects_router
from heliport.documentation.urls import router as documentation_router
from heliport.publication.urls import router as publication_router
from heliport.sharelatex.urls import router as sharelatex_router
from heliport.smb_files.urls import router as smb_router
from heliport.ssh.urls import router as ssh_router
from heliport.version_control.urls import router as version_control_router

urlpatterns = [
    # django.contrib apps
    path("admin/", admin.site.urls),
    # Third-party apps
    path("__debug__/", include("debug_toolbar.urls")),
    path("accounts/", include("allauth.urls")),
    path("health/", include("health_check.urls")),
    path("qr-code/", include("qr_code.urls", namespace="qr_code")),
    # heliport apps
    path("", include("heliport.core.urls")),
    path("", include("heliport.archive.urls")),
    path("", include("heliport.cwl_execution.urls")),
    path("", include("heliport.data_management_plan.urls")),
    path("", include("heliport.data_source.urls")),
    path("", include("heliport.digital_objects.urls")),
    path("", include("heliport.documentation.urls")),
    path("", include("heliport.publication.urls")),
    path("", include("heliport.sharelatex.urls")),
    path("", include("heliport.smb_files.urls")),
    path("", include("heliport.ssh.urls")),
    path("", include("heliport.tables.urls")),
    path("", include("heliport.version_control.urls")),
]

api_routers = [
    core_router,
    archive_router,
    cwl_router,
    dmp_router,
    data_source_router,
    digital_objects_router,
    documentation_router,
    publication_router,
    sharelatex_router,
    smb_router,
    ssh_router,
    version_control_router,
]

if settings.HELIPORT_GATE_ENABLED:
    from heliport.gate_connection.urls import router as gate_connection_router

    urlpatterns.append(path("", include("heliport.gate_connection.urls")))
    api_routers.append(gate_connection_router)

if settings.HELIPORT_UNICORE_ENABLED:
    urlpatterns.append(path("", include("heliport.unicore.urls")))

router = routers.DefaultRouter()
for api_router in api_routers:
    router.registry.extend(api_router.registry)

urlpatterns.append(path("api/", include(router.urls)))

heliport/core/views/digital_objects.py
# noqa: D100
# SPDX-FileCopyrightText: 2023 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: GPL-3.0-or-later

from django.conf import settings
from django.db.models import Q
from django.http import JsonResponse
from django.views.generic import DetailView, View
from rest_framework import status

from heliport.core.digital_object_resolution import resolve
from heliport.core.mixins import HeliportLoginRequiredMixin, HeliportProjectMixin
from heliport.core.models import Project
from heliport.core.utils.context import Context
from heliport.core.utils.exceptions import UserMessage
from heliport.core.utils.queries import ListOfQuerySets, digital_objects_by_type


class AsDigitalObjectView(HeliportProjectMixin, DetailView):
    """
    Creates a :class:`heliport.core.models.DigitalObject` instance given a
    :class:`heliport.core.digital_object_resolution.Resolvable` provided as GET or POST
    parameters and returns it as JSON using ``"pk"``, ``"digital_object_id"``, ``"url"``
    and ``"label"``. If an error occurs the JSON contains an ``"error"`` attribute.

    This uses
    :meth:`heliport.core.digital_object_interface.GeneralDigitalObject.as_digital_object``
    internally.

    If you set POST parameter `is_helper` to ``True`` the resulting digital object is
    marked as "helper". This can be used when querying digital objects to not show
    automatically generated helpers to the user.
    """  # noqa: D205

    model = Project
    pk_url_kwarg = "project"

    def post(self, request, *args, **kwargs):
        """Handle post."""
        project = self.get_object()
        user = None
        if hasattr(request.user, "heliportuser"):
            user = request.user.heliportuser
        with Context(user, project) as context:
            try:
                params = request.GET.copy()
                params.update(request.POST)
                obj = resolve(params, context)
                if obj is None:
                    raise UserMessage("Object not found")
                maybe_digital_object = obj.as_digital_object_if_exists(context)
                digital_object = maybe_digital_object.as_digital_object(context)
                if str(request.POST.get("is_helper")).lower() == "true":
                    digital_object.is_helper = True
                    digital_object.save()
                digital_object.projects.add(project)
                return JsonResponse(
                    {
                        "pk": digital_object.pk,
                        "digital_object_id": digital_object.digital_object_id,
                        "url": digital_object.local_url(request),
                        "label": digital_object.label,
                    }
                )
            except UserMessage as e:
                return JsonResponse(
                    {"error": e.message}, status=status.HTTP_400_BAD_REQUEST
                )


class DigitalObjectAutocompleteView(HeliportLoginRequiredMixin, View):
    """Handles getting information for autocomplete inputs for :class:`heliport.core.models.DigitalObject`."""  # noqa: E501

    def get(self, request, *args, **kwargs):
        """Responde to GET request.

        Returns json list like::

            [
                {"label": "aa", "pk": 1},
                {"label": "xa", "pk": 55}
            ]

        Excludes deleted objects and respects user rights.
        Maximum dumber of results is configurable in settings.py ``HELIPORT_CORE_AUTOCOMPLETE_COUNT``

        Supports the following get parameters:

            - ``type`` - Restrict autocomplete to a type. See :func:`heliport.core.utils.queries.digital_objects_by_type` for allowed values. ``...?type=1&type=2`` results in union of results to ``...?type=1`` and ``...?type=2``.
            - ``q`` or ``term`` - search term for label and persistent_id
            - ``exact`` - false (default): case-insensitive and allow part match; case_insensitive: case-insensitive full match; true: case-sensitive full match. psersistent_id is always matched exact
        """  # noqa: D401, E501
        query = ListOfQuerySets()

        obj_types = request.GET.getlist("type")
        if obj_types:
            for obj_type in obj_types:
                query.extend(digital_objects_by_type(obj_type))
        else:
            query.all_digital_objects()

        auth_user = request.user
        user = None
        if hasattr(auth_user, "heliportuser"):
            user = auth_user.heliportuser
        if user is None:
            query.filter(owner__isnull=True)
        else:
            query.filter(Q(owner__isnull=True) | Q(owner=user) | Q(co_owners=user))

        query.filter(deleted__isnull=True)

        pattern = request.GET.get("q") or request.GET.get("term", "")
        if pattern:
            exact = str(request.GET.get("exact", "false")).lower()
            if exact == "false":
                q = Q(label__icontains=pattern)
            elif exact == "case_insensitive":
                q = Q(label__iexact=pattern)
            else:
                q = Q(label__exact=pattern)

            query.filter(q | Q(persistent_id=pattern))

        return JsonResponse(
            [
                {"label": obj.label, "pk": obj.digital_object_id}
                for obj in query.as_list(settings.HELIPORT_CORE_AUTOCOMPLETE_COUNT)
            ],
            safe=False,
        )

heliport/core/templates/core/user/login_infos.html
{% extends "core/base/base.html" %}
{% comment %}
SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)

SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}
{% block title %}
  Remote Server Logins
{% endblock title %}
{% block content %}
  <h3 class="mb-3">Remote Server Logins</h3>
  <p>
    Logins added here can be used to access resources like files on remote servers or
    workstations.
  </p>
  {% if logins %}
    <form method="post">
      {% csrf_token %}
      <table class="table">
        <tr>
          <th style="width: 10%;">ID</th>
          <th style="width: 20%;">Type</th>
          <th style="width: 34%;">Name</th>
          <th></th>
        </tr>
        {% for login in logins %}
          <tr>
            <td class="align-middle">{{ login.login_info_id }}</td>
            <td class="align-middle">{{ login.type }}</td>
            <td class="align-middle">{{ login.name }}</td>
            <td class="align-middle">
              <div class="container">
                <div class="row">
                  {% if login.type == login_types.SSH %}
                    <div class="col-md d-grid text-nowrap ps-2 pe-0 py-1">
                      {% if login.connected %}
                        <a class="btn btn-warning {% if update %}disabled{% endif %}"
                           href="{% url 'core:remote_server_logout' login.pk %}">Disconnect</a>
                      {% else %}
                        <a class="btn btn-success {% if update %}disabled{% endif %}"
                           href="{% url 'core:remote_server_login' login.pk %}">Connect</a>
                      {% endif %}
                    </div>
                  {% else %}
                    <div class="col-md ps-2 pe-0" style="min-width: 33%"></div>
                  {% endif %}
                  <div class="col-md d-grid ps-2 pe-0 py-1">
                    <a class="btn btn-secondary {% if update or login.connected %}disabled{% endif %}"
                       href="{% url 'core:user_login_update' login.pk %}">Edit</a>
                  </div>
                  <div class="col-md d-grid ps-2 pe-0 py-1">
                    <button class="btn btn-danger"
                            {% if update %}disabled{% endif %}
                            name="remove"
                            value="{{ login.pk }}">Remove</button>
                  </div>
                </div>
              </div>
            </td>
          </tr>
        {% endfor %}
      </table>
    </form>
  {% endif %}
  <br />
  {% if update %}
    <h4>Update a Login</h4>
  {% else %}
    <h4>Add a Login</h4>
  {% endif %}
  <form method="post" x-data='{ type: "{{ login_type|default:"" }}" }'>
    {% csrf_token %}
    <table class="table">
      <tr>
        <th class="align-middle" style="width:30%">Login Type</th>
        <td>
          <select name="type"
                  id="type_select"
                  x-model="type"
                  class="form-select w-50"
                  required="required">
            <option value="" disabled selected>Choose a Login Type</option>
            {% for t in login_types %}<option value="{{ t }}">{{ t }}</option>{% endfor %}
          </select>
        </td>
      </tr>
      <tr id="name" style="display: none" x-show="type !== ''">
        <th class="align-middle" style="width:30%">Name of this login info</th>
        <td>
          <input name="name"
                 id="name_input"
                 value="{{ form.instance.name }}"
                 :required="type !== ''"
                 class="form-control w-50" />
        </td>
      </tr>
      <tr id="machine" style="display: none" x-show="type === 'ssh connection'">
        <th class="align-middle" style="width:30%">Machine</th>
        <td>
          <input name="machine"
                 id="machine_input"
                 value="{{ form.instance.machine }}"
                 :required="type === 'ssh connection'"
                 class="form-control w-50" />
        </td>
      </tr>
      <tr id="via" style="display: none" x-show="type === 'ssh connection'">
        <th class="align-middle" style="width:30%">Indirect via</th>
        <td>
          <select name="via" class="form-select w-50">
            <option value="">no indirect SSH connection</option>
            {% for possibility in ssh_logins %}
              <option value="{{ possibility.pk }}"
                      {% if possibility == object.via %}selected{% endif %}
                      {% if possibility == object %}disabled{% endif %}>{{ possibility.name }}</option>
            {% endfor %}
          </select>
        </td>
      </tr>
      <tr id="username_password"
          style="display: none"
          x-show="type === 'ssh connection'">
        <th class="align-middle" style="width:30%">
          Username
          / Password
        </th>
        <td>
          After adding a SSH login you can click the Connect button to log in.
          <br />
          That way we don't have to store your password.
        </td>
      </tr>
      <tr id="key"
          style="display: none"
          x-show="type === 'authentication token'">
        <th class="align-middle" style="width:30%">Token</th>
        <td>
          <input name="key"
                 id="key_input"
                 value="{{ form.instance.key }}"
                 :required="type === 'authentication token'"
                 class="form-control w-50" />
        </td>
      </tr>
      <tr id="username"
          style="display: none"
          x-show="type === 'username and password'">
        <th class="align-middle" style="width:30%">Username</th>
        <td>
          <input name="username"
                 id="username_input"
                 value="{{ form.instance.username }}"
                 :required="type === 'username and password'"
                 class="form-control w-50" />
        </td>
      </tr>
      <tr id="password"
          style="display: none"
          x-show="type === 'username and password'">
        <th class="align-middle" style="width:30%">Password</th>
        <td>
          <input name="password"
                 id="password_input"
                 value="{{ form.instance.password }}"
                 :required="type === 'username and password'"
                 class="form-control w-50"
                 type="password" />
        </td>
      </tr>
      <tr id="slurm" style="display: none" x-show="type === 'ssh connection'">
        <th class="align-middle" style="width:30%">Cluster with Slurm support</th>
        <td class="align-middle">
          <input name="slurm"
                 type="checkbox"
                 {% if form.instance.slurm %}checked{% endif %} />
        </td>
      </tr>
    </table>
    <table>
      <tr>
        {% if update %}
          <td style="padding-left: 0.75rem">
            <button class="btn btn-primary">Save</button>
          </td>
          <td style="padding-left: 0.75rem">
            <a class="btn btn-secondary" href="{% url 'core:user_login_list' %}">Cancel</a>
          </td>
        {% else %}
          <td style="padding-left: 0.75rem">
            <button class="btn btn-primary">Add</button>
          </td>
        {% endif %}
      </tr>
    </table>
    {{ form.errors }}
  </form>
{% endblock content %}

heliport/core/templates/core/user/remote_server_login.html
{% extends "core/base/base.html" %}
{% comment %}
SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)

SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}
{% block content %}
  <div class="row">
    <div class="col">
      <h3>Connect to {{ logininfo.machine }} Server</h3>
      <p>We do not store your password. It is required to connect to the remote machine once and transfer an SSH key.</p>
      {% if message %}
        <div class="alert alert-danger" role="alert">
          <small>{{ message }}</small>
        </div>
      {% endif %}
      <form method="post">
        {% csrf_token %}
        <div class="mb-3">
          <label class="form-label">Username</label>
          <input type="text" name="username" class="form-control" />
        </div>
        <div class="mb-3">
          <label class="form-label">Password</label>
          <input type="password" name="password" class="form-control" />
        </div>
        <input type="submit" class="btn btn-primary" value="Login" />
      </form>
    </div>
  </div>
{% endblock content %}

heliport/core/templates/core/user/tokens.html
{% extends "core/base/base.html" %}
{% comment %}
SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)

SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}
{% load static %}
{% load vendor_tags %}
{% block title %}
  HELIPORT API Tokens
{% endblock title %}
{% block content %}
  {% vendor_css "codemirror" %}
  <style>
    .expired-token-row{
        color: var(--bs-gray);
    }
    .token-row > td{
        vertical-align: middle;
    }
    .CodeMirror{
        height: 10em;
        margin-bottom: 2em;
    }
  </style>
  <div class="row">
    <div class="col">
      <h3>HELIPORT API Tokens</h3>
      {% comment %} trigger delete modal {% endcomment %}
      <button type="button"
              class="btn btn-danger mb-3"
              data-bs-toggle="modal"
              data-bs-target="#deleteTokenModal">Delete All Tokens</button>
      {% comment %} Delete Modal {% endcomment %}
      <div class="modal fade"
           id="deleteTokenModal"
           tabindex="-1"
           role="dialog"
           aria-labelledby="deleteTokenModalLabel"
           aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteTokenModalLabel">Delete All Tokens</h5>
              <button type="button"
                      class="btn-close"
                      data-bs-dismiss="modal"
                      aria-label="Close"></button>
            </div>
            <div class="modal-body">Are you sure you want to delete all Tokens for the HELIPORT API?</div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
              <button type="button" class="btn btn-danger" id="token-delete-all">Delete</button>
            </div>
          </div>
        </div>
      </div>
      {% comment %} Show Token Modal {% endcomment %}
      <div class="modal fade"
           id="showTokenModal"
           tabindex="-1"
           role="dialog"
           aria-labelledby="showTokenModalLabel"
           aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteTokenModalLabel">Your New Token</h5>
              <button type="button"
                      class="btn-close"
                      data-bs-dismiss="modal"
                      aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <p>Note that this token is not shown again.</p>
              <div class="input-group mb-3">
                <input type="text" class="form-control" id="token-show" readonly />
                <button class="btn btn-outline-secondary"
                        type="button"
                        id="token-to-clipboard">
                  <i class="fa-solid fa-clipboard"></i>
                </button>
              </div>
            </div>
            <div class="modal-footer">
              <a href="{% url 'core:user_token_list' %}"
                 class="btn btn-primary"
                 id="token-after-show"
                 onclick="window.location.reload();">OK</a>
            </div>
          </div>
        </div>
      </div>
      <table class="table">
        <tr>
          <th>Hash</th>
          <th>
            <label for="token-name">Name</label>
          </th>
          <th>Date created</th>
          <th>
            <label for="token-expiry">Date expiry</label>
          </th>
          <th></th>
        </tr>
        {% for token in tokens %}
          <tr class="token-row {% if token.expiry < now %}expired-token-row{% endif %}">
            <td>
              <a id="{{ token.pk }}">{{ token.digest|truncatechars:7 }}</a>
            </td>
            <td>{{ token.namedtoken.name }}</td>
            <td>{{ token.created }}</td>
            <td>
              {% if token.expiry %}
                {{ token.expiry }}
              {% else %}
                Never
              {% endif %}
            </td>
            <td>
              <button class="btn btn-danger" data-delete-token="{{ token.pk }}">Delete</button>
            </td>
          </tr>
        {% endfor %}
        <tr>
          <td class="align-middle">New</td>
          <td>
            <input id="token-name" class="form-control" />
          </td>
          <td class="align-middle"></td>
          <td>
            <input id="token-expiry"
                   type="date"
                   value="{{ tomorrow }}"
                   class="form-control" />
          </td>
          <td>
            <button class="btn btn-primary" id="token-create">Create</button>
          </td>
        </tr>
      </table>
      <p>Example how to use tokens using the third-party Python Requests package:</p>
      <textarea id="token-example" rows="6" cols="72" readonly>
import requests
response = requests.get(
    "{{ api_url }}",
    headers={"Authorization": "{{ auth_header_prefix }} {{ token_prefix }}123abc..."},
)
print(response.json())</textarea>
    </div>
  </div>
  <br />
{% endblock content %}
{% block script %}
  <script>
    $('button[data-delete-token]').click(event => {
        let button = $(event.target);
        let token = button.attr("data-delete-token");
        let table_row = button.closest("tr");
        $.post("{% url 'core:delete_token' %}",
            {
                pk: token,
                csrfmiddlewaretoken: "{{ csrf_token | escapejs }}"
            }, result => {
                table_row.remove();
            }
        );
    });
    $('#token-delete-all').click(event => {
        $.post("{% url 'core:logout_all_tokens' %}",
            {
                csrfmiddlewaretoken: "{{ csrf_token | escapejs }}"
            }, result => {
                $(".token-row").remove();
            }
        );
        $("#deleteTokenModal").modal("hide");
    });
    $('#token-create').click(event => {
        $.post("{% url 'core:login_named' %}",
            {
                csrfmiddlewaretoken: "{{ csrf_token | escapejs }}",
                expiry: $("#token-expiry").val(),
                name: $("#token-name").val()
            }, result => {
                $("#token-show").val(result["token"]);
                $("#token-after-show").attr("href", `{% url "core:user_token_list" %}#${result["hash"]}`);
                $("#showTokenModal").modal("show");
            }
        );
    });
    $("#token-to-clipboard").click(event => {
        let token_show = $("#token-show");
        navigator.clipboard.writeText(token_show.val());
        token_show.effect('highlight', {}, 2000);
    })
  </script>
  {% vendor_js "codemirror" %}
  <script>
    let token_example_area = document.getElementById('token-example');
    let code_mirror = CodeMirror.fromTextArea(token_example_area,
        {'lineNumbers': true, 'mode': 'python', 'readOnly': true}
    );
  </script>
{% endblock script %}