heliport/core/urls.py
# SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""Map django views to urls.

See this :ref:`django:topics/http/urls:example` including explanation from the Django
documentation.
"""

from django.conf import settings
from django.urls import include, path, re_path, reverse_lazy
from django.views.decorators.cache import cache_page
from django.views.generic import RedirectView
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView
from rest_framework import routers

from .views.api import (
    ContributionViewSet,
    DeleteAllTokensView,
    DigitalObjectAPI,
    GroupViewSet,
    LoginNamedTokenView,
    LogoutTokenView,
    MaintenanceMessageView,
    ProjectViewSet,
    TokenViewSet,
    UserViewSet,
)
from .views.digital_objects import AsDigitalObjectView, DigitalObjectAutocompleteView
from .views.images import ImagesView, ImageView, TakePictureView
from .views.landing_page import IndexView, LandingPageView, ResolveDigitalObjectView
from .views.project import (
    CreateProjectView,
    CreateSampleProjectView,
    ImportFromProjectView,
    OpenInProjectView,
    ProjectGraphView,
    ProjectListView,
    ProjectTimelineView,
    ProjectUpdateView,
    ProjectView,
    SubprojectsView,
    get_users_autocomplete,
)
from .views.search import SearchBaseView, SearchView
from .views.tags import TagAutocompleteView, TagJsonView, TagsView
from .views.user import (
    LoginInfoUpdateView,
    LoginInfoView,
    RemoteServerLoginView,
    RemoteServerLogoutView,
    TokenListView,
    UserProfileView,
)

app_name = "core"
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path(
        "about/",
        RedirectView.as_view(url=settings.HELIPORT_CORE_ABOUT_URL),
        name="about",
    ),
    path(
        "docs/", RedirectView.as_view(url=settings.HELIPORT_CORE_DOCS_URL), name="docs"
    ),
    path(
        "imprint/",
        RedirectView.as_view(url=settings.HELIPORT_CORE_IMPRINT_URL),
        name="imprint",
    ),
    path(
        "privacy/",
        RedirectView.as_view(url=settings.HELIPORT_CORE_PRIVACY_URL),
        name="privacy",
    ),
    path(
        "terms/", RedirectView.as_view(url=settings.HELIPORT_CORE_TOS_URL), name="tos"
    ),
    path(
        "cite/", RedirectView.as_view(url=settings.HELIPORT_CORE_CITE_URL), name="cite"
    ),
    # Auth is handled by allauth. The login, logout, and register URLs are kept for
    # their nice paths and potentially widely used names.
    path(
        "login/", RedirectView.as_view(url=reverse_lazy("account_login")), name="login"
    ),
    path(
        "logout/",
        RedirectView.as_view(url=reverse_lazy("account_logout")),
        name="logout",
    ),
    path(
        "register/",
        RedirectView.as_view(url=reverse_lazy("account_signup")),
        name="register",
    ),
    path("user/profile/", UserProfileView.as_view(), name="user_profile"),
    path("user/token/list/", TokenListView.as_view(), name="user_token_list"),
    path(
        "user/logout-all-tokens/",
        DeleteAllTokensView.as_view(),
        name="logout_all_tokens",
    ),
    path("user/login/list/", LoginInfoView.as_view(), name="user_login_list"),
    path(
        "user/login/<int:pk>/update/",
        LoginInfoUpdateView.as_view(),
        name="user_login_update",
    ),
    path(
        "user/login/remote-server-login/<int:pk>/",
        RemoteServerLoginView.as_view(),
        name="remote_server_login",
    ),
    path(
        "user/login/remote-server-logout/<int:pk>/",
        RemoteServerLogoutView.as_view(),
        name="remote_server_logout",
    ),
    path(
        "digital-object-autocomplete/",
        DigitalObjectAutocompleteView.as_view(),
        name="digital_object_autocomplete",
    ),
    # Redirect landing page URLs with missing "H" prefix.
    path(
        "object/<int:pk>/",
        RedirectView.as_view(
            permanent=True, pattern_name="core:landing_page", query_string=True
        ),
        name="legacy_landing_page",
    ),
    # Prefix "H" is required for XML serialization to work!
    path("object/H<int:pk>/", LandingPageView.as_view(), name="landing_page"),
    re_path(
        "object/(?P<identifier>.+)$",  # No trailing slash!
        ResolveDigitalObjectView.as_view(),
        name="resolve_digital_object_id",
    ),
    path("project/<int:project>/image/list/", ImagesView.as_view(), name="image_list"),
    path(
        "project/<int:project>/image/take/",
        TakePictureView.as_view(),
        name="take_image",
    ),
    path(
        "image/<int:pk>/data/",
        cache_page(4 * 24 * 60 * 60, cache="image_cache")(ImageView.as_view()),
        name="image_data",
    ),
    path("project/<int:project>/tag/list/", TagsView.as_view(), name="tag_list"),
    path(
        "project/<int:project>/tag/<int:pk>/update/",
        TagsView.as_view(),
        name="tag_update",
    ),
    path(
        "project/<int:project>/tag/list/json/",
        TagJsonView.as_view(),
        name="tag_json",
    ),
    path(
        "project/<int:project>/tag/autocomplete/",
        TagAutocompleteView.as_view(),
        name="tag_autocomplete",
    ),
    path(
        "project/<int:project>/subprojects/",
        SubprojectsView.as_view(),
        name="subprojects",
    ),
    path(
        "project/<int:project>/import/",
        ImportFromProjectView.as_view(),
        name="import_project",
    ),
    path("project/list/", ProjectListView.as_view(), name="project_list"),
    path(
        "project/create/sample/",
        CreateSampleProjectView.as_view(),
        name="project_create_sample",
    ),
    path("project/create/", CreateProjectView.as_view(), name="project_create"),
    path(
        "project/<int:project>/graph/", ProjectGraphView.as_view(), name="project_graph"
    ),
    path(
        "project/<int:project>/timeline/",
        ProjectTimelineView.as_view(),
        name="project_timeline",
    ),
    path("project/<int:project>/", ProjectView.as_view(), name="project"),
    path(
        "project/<int:project>/update/",
        ProjectUpdateView.as_view(),
        name="project_update",
    ),
    path("project/<int:project>/autocomplete-user/", get_users_autocomplete),
    path("search-base/", SearchBaseView.as_view(), name="search_base"),
    path("search/", SearchView.as_view(), name="search"),
    path(
        "project/<int:project>/as-digital-object/",
        AsDigitalObjectView.as_view(),
        name="as_digital_object",
    ),
    path(
        "project/<int:project>/redirect/",
        OpenInProjectView.as_view(),
        name="open_in_project",
    ),
]

# REST API
router = routers.DefaultRouter()
router.register(r"projects", ProjectViewSet, basename="projects")
router.register(r"users", UserViewSet, basename="users")
router.register(r"groups", GroupViewSet, basename="groups")
router.register(r"contributions", ContributionViewSet, basename="contributions")
router.register(r"tokens", TokenViewSet, basename="tokens")
router.register(
    r"digital-objects/complete", DigitalObjectAPI, basename="digital-objects-complete"
)

urlpatterns += [
    path("api/auth/delete-token/", LogoutTokenView.as_view(), name="delete_token"),
    path("api/auth/login-named/", LoginNamedTokenView.as_view(), name="login_named"),
    path("api/auth/", include("knox.urls")),
    path(
        "api/maintenance-message/",
        MaintenanceMessageView.as_view(),
        name="maintenance_message",
    ),
    path("openapi/", SpectacularAPIView.as_view(), name="openapi-schema"),
    path(
        "redoc/",
        SpectacularRedocView.as_view(url_name="core:openapi-schema"),
        name="redoc",
    ),
]

heliport_config/urls.py
# noqa: D100
# SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: GPL-3.0-or-later

from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from rest_framework import routers

from heliport.archive.urls import router as archive_router
from heliport.core.urls import router as core_router
from heliport.cwl_execution.urls import router as cwl_router
from heliport.data_management_plan.urls import router as dmp_router
from heliport.data_source.urls import router as data_source_router
from heliport.digital_objects.urls import router as digital_objects_router
from heliport.documentation.urls import router as documentation_router
from heliport.publication.urls import router as publication_router
from heliport.sharelatex.urls import router as sharelatex_router
from heliport.smb_files.urls import router as smb_router
from heliport.ssh.urls import router as ssh_router
from heliport.version_control.urls import router as version_control_router

urlpatterns = [
    # django.contrib apps
    path("admin/", admin.site.urls),
    # Third-party apps
    path("__debug__/", include("debug_toolbar.urls")),
    path("accounts/", include("allauth.urls")),
    path("health/", include("health_check.urls")),
    path("qr-code/", include("qr_code.urls", namespace="qr_code")),
    # heliport apps
    path("", include("heliport.core.urls")),
    path("", include("heliport.archive.urls")),
    path("", include("heliport.cwl_execution.urls")),
    path("", include("heliport.data_management_plan.urls")),
    path("", include("heliport.data_source.urls")),
    path("", include("heliport.digital_objects.urls")),
    path("", include("heliport.documentation.urls")),
    path("", include("heliport.publication.urls")),
    path("", include("heliport.sharelatex.urls")),
    path("", include("heliport.smb_files.urls")),
    path("", include("heliport.ssh.urls")),
    path("", include("heliport.tables.urls")),
    path("", include("heliport.version_control.urls")),
]

api_routers = [
    core_router,
    archive_router,
    cwl_router,
    dmp_router,
    data_source_router,
    digital_objects_router,
    documentation_router,
    publication_router,
    sharelatex_router,
    smb_router,
    ssh_router,
    version_control_router,
]

if settings.HELIPORT_GATE_ENABLED:
    from heliport.gate_connection.urls import router as gate_connection_router

    urlpatterns.append(path("", include("heliport.gate_connection.urls")))
    api_routers.append(gate_connection_router)

if settings.HELIPORT_UNICORE_ENABLED:
    urlpatterns.append(path("", include("heliport.unicore.urls")))

router = routers.DefaultRouter()
for api_router in api_routers:
    router.registry.extend(api_router.registry)

urlpatterns.append(path("api/", include(router.urls)))

heliport/core/views/digital_objects.py
# noqa: D100
# SPDX-FileCopyrightText: 2023 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: GPL-3.0-or-later

from django.conf import settings
from django.db.models import Q
from django.http import JsonResponse
from django.views.generic import DetailView, View
from rest_framework import status

from heliport.core.digital_object_resolution import resolve
from heliport.core.mixins import HeliportLoginRequiredMixin, HeliportProjectMixin
from heliport.core.models import Project
from heliport.core.utils.context import Context
from heliport.core.utils.exceptions import UserMessage
from heliport.core.utils.queries import ListOfQuerySets, digital_objects_by_type


class AsDigitalObjectView(HeliportProjectMixin, DetailView):
    """
    Creates a :class:`heliport.core.models.DigitalObject` instance given a
    :class:`heliport.core.digital_object_resolution.Resolvable` provided as GET or POST
    parameters and returns it as JSON using ``"pk"``, ``"digital_object_id"``, ``"url"``
    and ``"label"``. If an error occurs the JSON contains an ``"error"`` attribute.

    This uses
    :meth:`heliport.core.digital_object_interface.GeneralDigitalObject.as_digital_object``
    internally.

    If you set POST parameter `is_helper` to ``True`` the resulting digital object is
    marked as "helper". This can be used when querying digital objects to not show
    automatically generated helpers to the user.
    """  # noqa: D205

    model = Project
    pk_url_kwarg = "project"

    def post(self, request, *args, **kwargs):
        """Handle post."""
        project = self.get_object()
        user = None
        if hasattr(request.user, "heliportuser"):
            user = request.user.heliportuser
        with Context(user, project) as context:
            try:
                params = request.GET.copy()
                params.update(request.POST)
                obj = resolve(params, context)
                if obj is None:
                    raise UserMessage("Object not found")
                maybe_digital_object = obj.as_digital_object_if_exists(context)
                digital_object = maybe_digital_object.as_digital_object(context)
                if str(request.POST.get("is_helper")).lower() == "true":
                    digital_object.is_helper = True
                    digital_object.save()
                digital_object.projects.add(project)
                return JsonResponse(
                    {
                        "pk": digital_object.pk,
                        "digital_object_id": digital_object.digital_object_id,
                        "url": digital_object.local_url(request),
                        "label": digital_object.label,
                    }
                )
            except UserMessage as e:
                return JsonResponse(
                    {"error": e.message}, status=status.HTTP_400_BAD_REQUEST
                )


class DigitalObjectAutocompleteView(HeliportLoginRequiredMixin, View):
    """Handles getting information for autocomplete inputs for :class:`heliport.core.models.DigitalObject`."""  # noqa: E501

    def get(self, request, *args, **kwargs):
        """Responde to GET request.

        Returns json list like::

            [
                {"label": "aa", "pk": 1},
                {"label": "xa", "pk": 55}
            ]

        Excludes deleted objects and respects user rights.
        Maximum dumber of results is configurable in settings.py ``HELIPORT_CORE_AUTOCOMPLETE_COUNT``

        Supports the following get parameters:

            - ``type`` - Restrict autocomplete to a type. See :func:`heliport.core.utils.queries.digital_objects_by_type` for allowed values. ``...?type=1&type=2`` results in union of results to ``...?type=1`` and ``...?type=2``.
            - ``q`` or ``term`` - search term for label and persistent_id
            - ``exact`` - false (default): case-insensitive and allow part match; case_insensitive: case-insensitive full match; true: case-sensitive full match. psersistent_id is always matched exact
        """  # noqa: D401, E501
        query = ListOfQuerySets()

        obj_types = request.GET.getlist("type")
        if obj_types:
            for obj_type in obj_types:
                query.extend(digital_objects_by_type(obj_type))
        else:
            query.all_digital_objects()

        auth_user = request.user
        user = None
        if hasattr(auth_user, "heliportuser"):
            user = auth_user.heliportuser
        if user is None:
            query.filter(owner__isnull=True)
        else:
            query.filter(Q(owner__isnull=True) | Q(owner=user) | Q(co_owners=user))

        query.filter(deleted__isnull=True)

        pattern = request.GET.get("q") or request.GET.get("term", "")
        if pattern:
            exact = str(request.GET.get("exact", "false")).lower()
            if exact == "false":
                q = Q(label__icontains=pattern)
            elif exact == "case_insensitive":
                q = Q(label__iexact=pattern)
            else:
                q = Q(label__exact=pattern)

            query.filter(q | Q(persistent_id=pattern))

        return JsonResponse(
            [
                {"label": obj.label, "pk": obj.digital_object_id}
                for obj in query.as_list(settings.HELIPORT_CORE_AUTOCOMPLETE_COUNT)
            ],
            safe=False,
        )

heliport/core/templates/core/base/base.html
{% extends "core/base/wide_base.html" %}
{% comment %}
SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)

SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}
{% load bootstrap_utils %}
{% block wide_content %}
  <div class="container page mt-3">
    <div hx-trigger="load"
         hx-get="{% url 'core:maintenance_message' %}"
         hx-swap="outerHTML"></div>
    {% if messages %}
      {% for message in messages %}
        <div class="{% alert_classes_for_message_level message.level %}">
          <small>{{ message }}</small>
        </div>
      {% endfor %}
    {% endif %}
    {% block content %}
    {% endblock content %}
  </div>
{% endblock wide_content %}

heliport/core/templates/core/base/digital_object_autocomplete.html
{% comment %}
SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)

SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}
<script>
    function make_digital_object_autocomplete(pk_input, label_input) {
        let autocomplete_url = '{% url "core:digital_object_autocomplete" %}';
        let type_constraint = pk_input.attr('data-digital-object-type');

        let autocomplete_options = {
            autoFocus: true,
            source: autocomplete_url,
            select: (event, ui) => {
                pk_input.val(ui.item.pk);
            },
            response: (event, ui) => {
                let label_index = new Map();
                for (let suggestion of ui.content) {
                    let label_unique = !label_index.has(suggestion.label);
                    label_index.set(suggestion.label, label_unique);
                }
                for (let suggestion of ui.content) {
                    if (!label_index.get(suggestion.label)) suggestion.label = `${suggestion.label} (${suggestion.pk})`;
                }
            }
        }
        if (type_constraint !== undefined) {
            autocomplete_options['source'] = `${autocomplete_url}?type=${type_constraint}`
        }

        label_input.autocomplete(autocomplete_options);
    }

    function autocomplete_subtree(jquery_selector){
        for(let hidden_form_control_no_jquery of jquery_selector.find('input[data-digital-object-autocomplete]')) {
            let hidden_form_control = $(hidden_form_control_no_jquery);
            let base_id = hidden_form_control.attr('data-digital-object-autocomplete');
            let autocomplete_form_control = $(document.getElementById(base_id));
            let next_element = hidden_form_control.next();
            if(next_element.attr("id") === base_id) autocomplete_form_control = next_element;
            make_digital_object_autocomplete(hidden_form_control, autocomplete_form_control);
        }
    }

    autocomplete_subtree($("html"));
</script>

heliport/core/templates/core/base/footer.html
{% comment %}
SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)

SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}
{% load static %}
<footer class="footer mt-auto">
  <div class="container">
    <div class="row pt-3">
      <div class="col-12 col-sm-4 text-center">
        <div class="float-sm-start">
          <span title="HELIPORT {{ HELIPORT_VERSION_STRING }}">Powered by</span>
          <a href="https://www.hzdr.de" target="_blank">HZDR</a>,
          <a href="https://www.fz-juelich.de" target="_blank">FZJ</a>,
          <a href="https://www.hi-jena.de" target="_blank">HIJ</a> &amp;
          <a href="https://helmholtz-metadaten.de"
             target="_blank"
             class="hmc-angle-brackets">HMC</a>
        </div>
      </div>
      <div class="col-12 col-sm-4 text-center">
        Member of <a href="https://www.helmholtz.de" target="_blank">Helmholtz</a>
      </div>
      <div class="col-12 col-sm-4 text-center">
        <div class="float-sm-end">
          <ul class="list-inline">
            <li class="list-inline-item">
              <a href="{% url 'core:cite' %}" target="_blank">Cite</a>
            </li>
            <li class="list-inline-item">
              <a href="{% url 'core:imprint' %}" target="_blank">Imprint</a>
            </li>
            <li class="list-inline-item">
              <a href="{% url 'core:privacy' %}" target="_blank">Privacy Policy</a>
            </li>
            <li class="list-inline-item">
              <a href="{% url 'core:tos' %}" target="_blank">Terms of Use</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>

heliport/core/templates/core/base/navbar.html
{% comment %}
SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)

SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}
{% load static %}
<nav class="navbar heliport-navbar navbar-expand-lg navbar-light nav-fill">
  <div class="nav-container container">
    <a class="navbar-brand heliport-navbar-brand"
       {% if user.is_authenticated %}href="{% url 'core:project_list' %}"{% else %}href="{% url 'core:index' %}"{% endif %}>
      <img class="heliport-logo-large"
           alt="HELIPORT"
           height="44"
           width="206"
           src="{% static 'core/img/heliport_compact_dark.svg' %}" />
      <img class="heliport-logo-small"
           alt="HELIPORT"
           height="44"
           width="57"
           src="{% static 'core/img/heliport_small_dark.svg' %}" />
    </a>
    <button class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="w-100 d-flex justify-content-center nav-search">
      <form action="{% url 'core:search_base' %}">
        {% csrf_token %}
        <div class="input-group">
          {% comment %}
          HELIPORT has different search functionalities that use the `q` parameter. In
          order not to show e.g. the GATE project search query in this text box we only
          fill in a value when on the search page.
          {% endcomment %}
          <input class="form-control"
                 type="search"
                 placeholder="Search"
                 aria-label="Search"
                 {% if request.resolver_match.url_name == "search_base" %}value="{{ request.GET.q|default_if_none:'' }}"{% endif %}
                 name="q" />
          <button class="btn btn-light" type="submit">
            <i class="fa-solid fa-magnifying-glass"></i>
          </button>
        </div>
      </form>
    </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link heliport-nav-link"
             href="{% url 'core:about' %}"
             target="_blank">
            <i class="fa-solid fa-info me-1"></i>
            About
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link heliport-nav-link"
             href="{% url 'core:docs' %}"
             target="_blank">
            <i class="fa-solid fa-book-atlas me-1"></i>
            Docs
          </a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link heliport-nav-link dropdown-toggle"
               href="#"
               id="navbarUserDropdown"
               role="button"
               data-bs-toggle="dropdown"
               aria-haspopup="true"
               aria-expanded="false">
              <i class="fa-solid fa-user me-1"></i>
              {{ user }}
            </a>
            <div class="dropdown-menu dropdown-menu-end"
                 aria-labelledby="navbarUserDropdown">
              <a class="dropdown-item" href="{% url 'core:user_profile' %}">
                <i class="fa-solid fa-user-gear me-1"></i>
                Profile
              </a>
              {% if OIDC_ENABLED %}
                <a class="dropdown-item" href="{% url 'socialaccount_connections' %}">
                  <i class="fa-solid fa-link me-1"></i>
                  Account Connections
                </a>
              {% endif %}
              <a class="dropdown-item" href="{% url 'account_change_password' %}">
                <i class="fa-solid fa-lock me-1"></i>
                Set / Change Password
              </a>
              <a class="dropdown-item" href="{% url 'account_email' %}">
                <i class="fa-solid fa-envelope me-1"></i>
                Change Email
              </a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'core:user_login_list' %}">
                <i class="fa-solid fa-server me-1"></i>
                Remote Server Logins
              </a>
              <a class="dropdown-item" href="{% url 'core:user_token_list' %}">
                <i class="fa-solid fa-key me-1"></i>
                API Tokens
              </a>
              <div class="dropdown-divider"></div>
              <form action="{% url 'account_logout' %}" method="post">
                {% csrf_token %}
                <button class="dropdown-item">
                  <i class="fa-solid fa-arrow-right-from-bracket me-1"></i>
                  Sign Out
                </button>
              </form>
            </div>
          </li>
        {% else %}
          <li class="nav-item dropdown">
            <a class="nav-link heliport-nav-link dropdown-toggle"
               href="#"
               id="navbarUserDropdown"
               role="button"
               data-bs-toggle="dropdown"
               aria-haspopup="true"
               aria-expanded="false">
              <i class="fa-solid fa-arrow-right-to-bracket me-1"></i>
              Sign In
            </a>
            <div class="dropdown-menu dropdown-menu-end"
                 aria-labelledby="navbarUserDropdown">
              <a class="dropdown-item" href="{% url 'account_login' %}">
                <i class="fa-solid fa-arrow-right-to-bracket me-1"></i>
                Sign In
              </a>
              {% if LOCAL_ACCOUNT_SIGNUP %}
                <a class="dropdown-item" href="{% url 'account_signup' %}">
                  <i class="fa-solid fa-dungeon me-1"></i>
                  Sign Up
                </a>
              {% endif %}
            </div>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
{% if project and project_dropdown_modules and project_navbar_modules %}
  <div class="navbar heliport-navbar-project navbar-expand-lg navbar-light nav-fill">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb heliport-breadcrumb">
          <li class="breadcrumb-item d-flex heliport-breadcrumb-item">
            <a href="{% url 'core:project_list' %}"
               class="heliport-breadcrumb-link"
               title="Project list">
              <i class="fa-solid fa-house"></i>
            </a>
          </li>
          {% for label, url in project_header_breadcrumbs %}
            {% if forloop.last %}
              <li class="breadcrumb-item d-flex heliport-breadcrumb-item active"
                  aria-current="page">
                <span class="heliport-breadcrumb-link">{{ label }}</span>
              </li>
            {% else %}
              <li class="breadcrumb-item d-flex heliport-breadcrumb-item">
                <a href="{{ url }}" class="heliport-breadcrumb-link">{{ label }}</a>
              </li>
            {% endif %}
          {% endfor %}
        </ol>
      </nav>
      <nav>
        <ul class="navbar-nav">
          {# TODO: Make these not clickable when on the page they represent #}
          {% for module in project_navbar_modules.included %}
            <li class="nav-item">
              <a class="nav-link heliport-nav-link"
                 href="{{ module.url }}"
                 role="button">
                <span class="{{ module.icon }} me-1"></span>
                {{ module.name }}
              </a>
            </li>
          {% endfor %}
          <li class="nav-item dropdown">
            <a class="nav-link heliport-nav-link dropdown-toggle"
               href="#"
               id="navbarProjectDropdown"
               role="button"
               data-bs-toggle="dropdown"
               aria-haspopup="true"
               aria-expanded="false">
              <i class="fa-solid fa-gears me-1"></i>
              Project
            </a>
            <div class="dropdown-menu dropdown-menu-end"
                 aria-labelledby="navbarProjectDropdown">
              {% for module in project_dropdown_modules.included %}
                <a class="dropdown-item" href="{{ module.url }}">
                  <span class="{{ module.icon }} me-1"></span>
                  {{ module.name }}
                </a>
              {% endfor %}
            </div>
          </li>
        </ul>
      </nav>
    </div>
  </div>
{% endif %}

heliport/core/templates/core/base/no_message_base.html
{% extends "core/base/wide_base.html" %}
{% comment %}
SPDX-FileCopyrightText: 2024 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)

SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}
{% block wide_content %}
  <div class="container page mt-3">
    {% block content %}
    {% endblock content %}
  </div>
{% endblock wide_content %}