heliport/core/urls.py
# SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""Map django views to urls.

See this :ref:`django:topics/http/urls:example` including explanation from the Django
documentation.
"""

from django.conf import settings
from django.urls import include, path, re_path, reverse_lazy
from django.views.decorators.cache import cache_page
from django.views.generic import RedirectView
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView
from rest_framework import routers

from .views.api import (
    ContributionViewSet,
    DeleteAllTokensView,
    DigitalObjectAPI,
    GroupViewSet,
    LoginNamedTokenView,
    LogoutTokenView,
    MaintenanceMessageView,
    ProjectViewSet,
    TokenViewSet,
    UserViewSet,
)
from .views.digital_objects import AsDigitalObjectView, DigitalObjectAutocompleteView
from .views.images import ImagesView, ImageView, TakePictureView
from .views.landing_page import IndexView, LandingPageView, ResolveDigitalObjectView
from .views.project import (
    CreateProjectView,
    CreateSampleProjectView,
    ImportFromProjectView,
    OpenInProjectView,
    ProjectGraphView,
    ProjectListView,
    ProjectTimelineView,
    ProjectUpdateView,
    ProjectView,
    SubprojectsView,
    get_users_autocomplete,
)
from .views.search import SearchBaseView, SearchView
from .views.tags import TagAutocompleteView, TagJsonView, TagsView
from .views.user import (
    LoginInfoUpdateView,
    LoginInfoView,
    RemoteServerLoginView,
    RemoteServerLogoutView,
    TokenListView,
    UserProfileView,
)

app_name = "core"
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path(
        "about/",
        RedirectView.as_view(url=settings.HELIPORT_CORE_ABOUT_URL),
        name="about",
    ),
    path(
        "docs/", RedirectView.as_view(url=settings.HELIPORT_CORE_DOCS_URL), name="docs"
    ),
    path(
        "imprint/",
        RedirectView.as_view(url=settings.HELIPORT_CORE_IMPRINT_URL),
        name="imprint",
    ),
    path(
        "privacy/",
        RedirectView.as_view(url=settings.HELIPORT_CORE_PRIVACY_URL),
        name="privacy",
    ),
    path(
        "terms/", RedirectView.as_view(url=settings.HELIPORT_CORE_TOS_URL), name="tos"
    ),
    path(
        "cite/", RedirectView.as_view(url=settings.HELIPORT_CORE_CITE_URL), name="cite"
    ),
    # Auth is handled by allauth. The login, logout, and register URLs are kept for
    # their nice paths and potentially widely used names.
    path(
        "login/", RedirectView.as_view(url=reverse_lazy("account_login")), name="login"
    ),
    path(
        "logout/",
        RedirectView.as_view(url=reverse_lazy("account_logout")),
        name="logout",
    ),
    path(
        "register/",
        RedirectView.as_view(url=reverse_lazy("account_signup")),
        name="register",
    ),
    path("user/profile/", UserProfileView.as_view(), name="user_profile"),
    path("user/token/list/", TokenListView.as_view(), name="user_token_list"),
    path(
        "user/logout-all-tokens/",
        DeleteAllTokensView.as_view(),
        name="logout_all_tokens",
    ),
    path("user/login/list/", LoginInfoView.as_view(), name="user_login_list"),
    path(
        "user/login/<int:pk>/update/",
        LoginInfoUpdateView.as_view(),
        name="user_login_update",
    ),
    path(
        "user/login/remote-server-login/<int:pk>/",
        RemoteServerLoginView.as_view(),
        name="remote_server_login",
    ),
    path(
        "user/login/remote-server-logout/<int:pk>/",
        RemoteServerLogoutView.as_view(),
        name="remote_server_logout",
    ),
    path(
        "digital-object-autocomplete/",
        DigitalObjectAutocompleteView.as_view(),
        name="digital_object_autocomplete",
    ),
    # Redirect landing page URLs with missing "H" prefix.
    path(
        "object/<int:pk>/",
        RedirectView.as_view(
            permanent=True, pattern_name="core:landing_page", query_string=True
        ),
        name="legacy_landing_page",
    ),
    # Prefix "H" is required for XML serialization to work!
    path("object/H<int:pk>/", LandingPageView.as_view(), name="landing_page"),
    re_path(
        "object/(?P<identifier>.+)$",  # No trailing slash!
        ResolveDigitalObjectView.as_view(),
        name="resolve_digital_object_id",
    ),
    path("project/<int:project>/image/list/", ImagesView.as_view(), name="image_list"),
    path(
        "project/<int:project>/image/take/",
        TakePictureView.as_view(),
        name="take_image",
    ),
    path(
        "image/<int:pk>/data/",
        cache_page(4 * 24 * 60 * 60, cache="image_cache")(ImageView.as_view()),
        name="image_data",
    ),
    path("project/<int:project>/tag/list/", TagsView.as_view(), name="tag_list"),
    path(
        "project/<int:project>/tag/<int:pk>/update/",
        TagsView.as_view(),
        name="tag_update",
    ),
    path(
        "project/<int:project>/tag/list/json/",
        TagJsonView.as_view(),
        name="tag_json",
    ),
    path(
        "project/<int:project>/tag/autocomplete/",
        TagAutocompleteView.as_view(),
        name="tag_autocomplete",
    ),
    path(
        "project/<int:project>/subprojects/",
        SubprojectsView.as_view(),
        name="subprojects",
    ),
    path(
        "project/<int:project>/import/",
        ImportFromProjectView.as_view(),
        name="import_project",
    ),
    path("project/list/", ProjectListView.as_view(), name="project_list"),
    path(
        "project/create/sample/",
        CreateSampleProjectView.as_view(),
        name="project_create_sample",
    ),
    path("project/create/", CreateProjectView.as_view(), name="project_create"),
    path(
        "project/<int:project>/graph/", ProjectGraphView.as_view(), name="project_graph"
    ),
    path(
        "project/<int:project>/timeline/",
        ProjectTimelineView.as_view(),
        name="project_timeline",
    ),
    path("project/<int:project>/", ProjectView.as_view(), name="project"),
    path(
        "project/<int:project>/update/",
        ProjectUpdateView.as_view(),
        name="project_update",
    ),
    path("project/<int:project>/autocomplete-user/", get_users_autocomplete),
    path("search-base/", SearchBaseView.as_view(), name="search_base"),
    path("search/", SearchView.as_view(), name="search"),
    path(
        "project/<int:project>/as-digital-object/",
        AsDigitalObjectView.as_view(),
        name="as_digital_object",
    ),
    path(
        "project/<int:project>/redirect/",
        OpenInProjectView.as_view(),
        name="open_in_project",
    ),
]

# REST API
router = routers.DefaultRouter()
router.register(r"projects", ProjectViewSet, basename="projects")
router.register(r"users", UserViewSet, basename="users")
router.register(r"groups", GroupViewSet, basename="groups")
router.register(r"contributions", ContributionViewSet, basename="contributions")
router.register(r"tokens", TokenViewSet, basename="tokens")
router.register(
    r"digital-objects/complete", DigitalObjectAPI, basename="digital-objects-complete"
)

urlpatterns += [
    path("api/auth/delete-token/", LogoutTokenView.as_view(), name="delete_token"),
    path("api/auth/login-named/", LoginNamedTokenView.as_view(), name="login_named"),
    path("api/auth/", include("knox.urls")),
    path(
        "api/maintenance-message/",
        MaintenanceMessageView.as_view(),
        name="maintenance_message",
    ),
    path("openapi/", SpectacularAPIView.as_view(), name="openapi-schema"),
    path(
        "redoc/",
        SpectacularRedocView.as_view(url_name="core:openapi-schema"),
        name="redoc",
    ),
]

heliport/unicore/urls.py
# SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""Map django views to urls.

See this :ref:`django:topics/http/urls:example` including explanation from the Django
documentation.
"""

from django.urls import path, re_path

from .views import (
    CallbackView,
    JobActionView,
    JobDetailView,
    JobsView,
    StorageView,
    TestJobView,
)

app_name = "unicore"
urlpatterns = [
    path("project/<int:project>/unicore/job/list/", JobsView.as_view(), name="jobs"),
    path(
        "project/<int:project>/unicore/job/<int:job>/",
        JobDetailView.as_view(),
        name="job-detail",
    ),
    path(
        "project/<int:project>/unicore/storage/list/",
        StorageView.as_view(),
        name="storage-list",
    ),
    path(
        "unicore/job/<str:job_id>/<str:action>/",
        JobActionView.as_view(),
        name="job-action",
    ),
    re_path("unicore/notify/?", CallbackView.as_view(), name="callback"),
    path("unicore/test-job/", TestJobView.as_view(), name="test-job"),
]

heliport_config/urls.py
# noqa: D100
# SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: GPL-3.0-or-later

from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from rest_framework import routers

from heliport.archive.urls import router as archive_router
from heliport.core.urls import router as core_router
from heliport.cwl_execution.urls import router as cwl_router
from heliport.data_management_plan.urls import router as dmp_router
from heliport.data_source.urls import router as data_source_router
from heliport.digital_objects.urls import router as digital_objects_router
from heliport.documentation.urls import router as documentation_router
from heliport.publication.urls import router as publication_router
from heliport.sharelatex.urls import router as sharelatex_router
from heliport.smb_files.urls import router as smb_router
from heliport.ssh.urls import router as ssh_router
from heliport.version_control.urls import router as version_control_router

urlpatterns = [
    # django.contrib apps
    path("admin/", admin.site.urls),
    # Third-party apps
    path("__debug__/", include("debug_toolbar.urls")),
    path("accounts/", include("allauth.urls")),
    path("health/", include("health_check.urls")),
    path("qr-code/", include("qr_code.urls", namespace="qr_code")),
    # heliport apps
    path("", include("heliport.core.urls")),
    path("", include("heliport.archive.urls")),
    path("", include("heliport.cwl_execution.urls")),
    path("", include("heliport.data_management_plan.urls")),
    path("", include("heliport.data_source.urls")),
    path("", include("heliport.digital_objects.urls")),
    path("", include("heliport.documentation.urls")),
    path("", include("heliport.publication.urls")),
    path("", include("heliport.sharelatex.urls")),
    path("", include("heliport.smb_files.urls")),
    path("", include("heliport.ssh.urls")),
    path("", include("heliport.tables.urls")),
    path("", include("heliport.version_control.urls")),
]

api_routers = [
    core_router,
    archive_router,
    cwl_router,
    dmp_router,
    data_source_router,
    digital_objects_router,
    documentation_router,
    publication_router,
    sharelatex_router,
    smb_router,
    ssh_router,
    version_control_router,
]

if settings.HELIPORT_GATE_ENABLED:
    from heliport.gate_connection.urls import router as gate_connection_router

    urlpatterns.append(path("", include("heliport.gate_connection.urls")))
    api_routers.append(gate_connection_router)

if settings.HELIPORT_UNICORE_ENABLED:
    urlpatterns.append(path("", include("heliport.unicore.urls")))

router = routers.DefaultRouter()
for api_router in api_routers:
    router.registry.extend(api_router.registry)

urlpatterns.append(path("api/", include(router.urls)))

heliport/unicore/templates/unicore/info.html
{% comment %}
SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)

SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}
<div id="infoBlock">
  <div class="card">
    <div class="card-header" id="headingInfo">
      <button class="btn collapsed"
              data-bs-toggle="collapse"
              data-bs-target="#collapseInfo"
              aria-expanded="false"
              aria-controls="collapseInfo">Interaction between HELIPORT and UNICORE</button>
    </div>
    <div id="collapseInfo"
         class="collapse"
         aria-labelledby="headingInfo"
         data-bs-parent="#infoBlock">
      <div class="card-body">
        <p>
          UNICORE instance: <code>{{ unicore_rest_core_url }}</code>
        </p>
        {% if unicore_has_login %}
          <p>
            HELIPORT can automatically pick up your UNICORE jobs. To associate a UNICORE job with
            {% if unicore_job_tag_project %}
              <b>this</b>
            {% else %}
              a
            {% endif %}
            HELIPORT project, add the tag
            {% if unicore_job_tag_project %}
              <span class="badge rounded-pill bg-primary">{{ unicore_job_tag_project }}</span>
            {% else %}
              <span class="badge rounded-pill bg-primary">{{ unicore_job_tag_prefix }}-ID</span>
            {% endif %}
            to your job description's <code>Tags</code> list.
            {% if not unicore_job_tag_project %}
              <code>ID</code> has to be replaced with your HELIPORT project ID which you can
              find in the URL of your project's page.
            {% endif %}
            <a href="{% url 'unicore:test-job' %}{% if project %}?project={{ project.pk }}{% endif %}">Start a test job.</a>
          </p>
          <p>
            If you want UNICORE to notify HELIPORT about changes of your job's status
            (running, completed, failed, ...), set the <code>Notification</code> field of the
            job description to <code>{{ unicore_callback_url }}</code>. (Please note: Currently,
            no action is performed when HELIPORT receives this notification.)
          </p>
          <p>
            More infos on UNICORE job descriptions can be found in the
            <a href="https://sourceforge.net/p/unicore/wiki/Job_Description/">UNICORE Wiki</a>.
          </p>
        {% else %}
          <p>
            Please <a href="{% url 'core:user_login_list' %}">add your UNICORE login</a> as
            a "username and password" login with the name "UNICORE".
          </p>
        {% endif %}
      </div>
    </div>
  </div>
</div>
<br />
{% if unicore_authentication_failed %}
  <div class="alert alert-danger">
    Could not authenticate with UNICORE server. Please enter the correct credentials for
    your "UNICORE" login <a href="{% url 'core:user_login_list' %}">here</a>.
  </div>
{% endif %}

heliport/unicore/templates/unicore/job-list.html
{% comment %}
SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)

SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}
{% if unicore_project_job_list %}
  <p>Project Jobs:</p>
  <ul>
    {% for job in unicore_project_job_list %}
      <li>
        <a href="{% url 'unicore:job-detail' project.pk job.properties.pk %}">{{ job.properties.name }} ({{ job.job_id | truncatechars:8 }})</a> @ {{ job.properties.siteName }}
        {% if job.properties.storage %}
          <a href="{{ job.properties.storage.resource_url }}">
            <i class="fa-solid fa-hard-drive text-black" title="Storage"></i>
          </a>
        {% endif %}
        {% if job.is_running %}
          <i class="fa-solid fa-person-running"
             title="Running, {{ job.properties.status }}"></i>
          <a href="{% url 'unicore:job-action' job.job_id 'abort' %}{% if project %}?project={{ project.pk }}{% endif %}">
            <i class="fa-solid fa-ban text-black" title="Abort"></i>
          </a>
        {% else %}
          {% if job.properties.status == 'SUCCESSFUL' %}
            <i class="fa-solid fa-circle-check text-success" title="Successful"></i>
          {% elif job.properties.status == 'FAILED' %}
            <i class="fa-solid fa-circle-xmark text-danger" title="Failed"></i>
          {% else %}
            <i class="fa-solid fa-circle-question text-black"
               title="Status: {{ job.properties.status }}"></i>
          {% endif %}
          <a href="{% url 'unicore:job-action' job.job_id 'restart' %}{% if project %}?project={{ project.pk }}{% endif %}">
            <i class="fa-solid fa-arrow-rotate-right text-black" title="Restart"></i>
          </a>
          <a href="{% url 'unicore:job-action' job.job_id 'delete' %}{% if project %}?project={{ project.pk }}{% endif %}">
            <i class="fa-solid fa-trash text-black" title="Delete"></i>
          </a>
        {% endif %}
        {% if job.properties.tags %}
          <br />
          {% for tag in job.properties.tags %}
            <span class="badge rounded-pill {% if tag == unicore_job_tag_project %}bg-primary{% else %}bg-secondary{% endif %}">
              {{ tag }}
            </span>
          {% endfor %}
        {% endif %}
        <p>Submitted {{ job.properties.submissionTimeDateTime }}</p>
      </li>
    {% endfor %}
  </ul>
{% endif %}
<hr />
{% if unicore_other_job_list %}
  <p>Other Jobs:</p>
  <ul>
    {% for job in unicore_other_job_list %}
      <li>
        {{ job.properties.name }} ({{ job.job_id | truncatechars:8 }}) @ {{ job.properties.siteName }}
        {% if job.properties.storage %}
          <a href="{{ job.properties.storage.resource_url }}">
            <i class="fa-solid fa-hard-drive text-black" title="Storage"></i>
          </a>
        {% endif %}
        {% if job.is_running %}
          <i class="fa-solid fa-person-running"
             title="Running, {{ job.properties.status }}"></i>
          <a href="{% url 'unicore:job-action' job.job_id 'abort' %}{% if project %}?project={{ project.pk }}{% endif %}">
            <i class="fa-solid fa-ban text-black" title="Abort"></i>
          </a>
        {% else %}
          {% if job.properties.status == 'SUCCESSFUL' %}
            <i class="fa-solid fa-circle-check text-success" title="Successful"></i>
          {% elif job.properties.status == 'FAILED' %}
            <i class="fa-solid fa-circle-xmark text-danger" title="Failed"></i>
          {% else %}
            <i class="fa-solid fa-circle-question text-black"
               title="Status: {{ job.properties.status }}"></i>
          {% endif %}
        {% endif %}
        {% if job.properties.tags %}
          <br />
          {% for tag in job.properties.tags %}
            <span class="badge rounded-pill {% if tag == unicore_job_tag_project %}bg-primary{% else %}bg-secondary{% endif %}">
              {{ tag }}
            </span>
          {% endfor %}
        {% endif %}
        <p>Submitted {{ job.properties.submissionTimeDateTime }}</p>
      </li>
    {% endfor %}
  </ul>
{% endif %}

heliport/unicore/templates/unicore/job.html
{% extends "core/base/base.html" %}
{% comment %}
SPDX-FileCopyrightText: 2023 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)

SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}
{% load heliport %}
{% block content %}
  <style>
    .log {
      color: var(--bs-white);
      background-color: #101020;
      font-family: 'Fira Mono', monospace;
      padding: 2em;
      margin-bottom: 2em;
      border: solid gray 3px;
      overflow-y: scroll;
      max-height: 95vh;
    }
  </style>
  <div class="log">
    {% for line in unicore_job.properties.log %}
      {{ line | linebreaksbr }}
      <br />
    {% endfor %}
  </div>
{% endblock content %}

heliport/unicore/templates/unicore/jobs.html
{% extends "core/base/base.html" %}
{% comment %}
SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)

SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}
{% block content %}
  {% include "unicore/info.html" %}
  {% include "unicore/job-list.html" %}
{% endblock content %}

heliport/unicore/templates/unicore/storages.html
{% extends "core/base/base.html" %}
{% comment %}
SPDX-FileCopyrightText: 2023 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)

SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}
{% load heliport %}
{% block content %}
  <style>
    td {
      vertical-align: middle !important;
    }

    .table-button {
      padding: 0.25em 0 0.25em 0.5em;
    }
  </style>
  <h3>UNICORE Storages</h3>
  {% if storages %}
    <form method="post">
      {% csrf_token %}
      <table class="table" x-data="{show_helpers: true}">
        <tr>
          <th style="width: 10%">ID</th>
          <th>Name</th>
          <th>Description</th>
          <th>
            {% if helper_exists %}
              <label>
                <input type="checkbox" x-model="show_helpers" />
                Show automatically created
              </label>
            {% endif %}
          </th>
        </tr>
        {% for storage, actions in storages|zip:storage_actions %}
          <tr {% if storage.is_helper %}x-show="show_helpers"{% endif %}>
            <td>{{ storage.pk }}</td>
            <td>{{ storage.label }}</td>
            <td>{{ storage.description }}</td>
            <td>
              <div class="container">
                <div class="row">
                  {% for action in actions %}
                    <div class="col-md d-grid table-button">
                      <a class="btn btn-primary" href="{{ action.link }}">{{ action.name }}</a>
                    </div>
                  {% endfor %}
                  <div class="col-md d-grid table-button">
                    <button class="btn btn-danger"
                            name="delete"
                            value="{{ storage.digital_object_id }}">Delete</button>
                  </div>
                </div>
              </div>
            </td>
          </tr>
        {% endfor %}
      </table>
    </form>
  {% endif %}
  <h4>Add one of your UNICORE storages to this project</h4>
  <form method="post">
    {% csrf_token %}
    <table class="table" x-data="{include_from_jobs: false}">
      <tr>
        <th>Name</th>
        <th style="width: 30%;">
          {% if storages_from_job_available %}
            <label>
              <input type="checkbox" x-model="include_from_jobs" />
              Include Storages from Jobs
            </label>
          {% endif %}
        </th>
      </tr>
      {% for storage, actions in available_storages|zip:available_storages_actions %}
        <tr {% if storage.for_job %}x-show="include_from_jobs" style="display: none;"{% endif %}>
          <td>{{ storage }}</td>
          <td>
            <div class="container">
              <div class="row">
                <div class="col-md d-grid table-button">
                  <button class="btn btn-primary"
                          name="add"
                          value="{{ storage.storage_url }}"
                          {% if storage.is_imported %}title="This storage is already imported" disabled="disabled"{% endif %}>
                    Add
                  </button>
                </div>
                {% for action in actions %}
                  <div class="col-md d-grid table-button">
                    <a class="btn btn-secondary" href="{{ action.link }}">{{ action.name }}</a>
                  </div>
                {% endfor %}
              </div>
            </div>
          </td>
        </tr>
      {% endfor %}
    </table>
  </form>
{% endblock content %}